name: Tacors UNO Direct Selling
favicon: null
layout_spectrum: 0.30325729632750154
typography_spectrum: 0.39963143575005233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4812491775956005
  lightness: 0.9369112693239003
  saturation: 0.19754294259473681
  rhythmicContrast: 0.914831698872149
purpose: []
